### ISSUE TITLE
Support for `main` branch

### ISSUE THREAD

**Issue by ch2ch3** [arnau/git-absorb#1]
👋 &nbsp;@arnau!

All these years, I have been a happy user of `git-absorb` and it's become part of my muscle memory :)

Today my work repositories have switched to using the `main` branch instead of `master`. Unfortunately, this library does not allow for a configurable base branch, and the reference to `master` is hardcoded (https://github.com/arnau/git-absorb/blob/master/src/main.rs#L39).

```
Current branch "<BRANCH_NAME>"
Checking out master ...
error: pathspec 'master' did not match any file(s) known to git
```

Any chance of getting an update? Alternatively, any pointers for me if I were to try and patch this?

**Comment by arnau** [comment]
Hey! hope all is well with you,

I looked at the codebase and it is quite a hack 🙄 I made a few updates to make it more flexible though. Version 0.2.0 changes:

* You can pass the base branch (e.g. `main`)
* You can pass the remote (defaults to `origin`)
* If no base branch is passed, attempts to use `main`, fallback to `master` otherwise. If `master` fails as well, it aborts.

**Comment by arnau** [comment]
Some time ago I removed the homebrew installation so you'll have to use the artifacts from https://github.com/arnau/git-absorb/releases/tag/v0.2.0

**Comment by ch2ch3** [comment]
That's amazing, thank you so much!
